import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <h1>Home page</h1>
          <Link href="/first-blog/first-blog" >
              <a>go to my-first-blog</a>
          </Link>
      </main>
    </div>
  )
}
